#!/bin/bash

# Just posting a bunch

curl -s -X POST -d '{"who":"testuser","message":"post number 1.","clock":3}'  http://localhost:8080/api/post && echo "done1" &
curl -s -X POST -d '{"who":"testuser","message":"post number 2.","clock":3}'  http://localhost:8080/api/post && echo "done2" &
curl -s -X POST -d '{"who":"testuser","message":"post number 3.","clock":3}'  http://localhost:8080/api/post && echo "done3" &
curl -s -X POST -d '{"who":"testuser","message":"post number 4.","clock":3}'  http://localhost:8080/api/post && echo "done4" &
curl -s -X POST -d '{"who":"testuser","message":"post number 5.","clock":3}'  http://localhost:8080/api/post && echo "done5" &
curl -s -X POST -d '{"who":"testuser","message":"post number 6.","clock":3}'  http://localhost:8080/api/post && echo "done6" &
curl -s -X POST -d '{"who":"testuser","message":"post number 7.","clock":3}'  http://localhost:8080/api/post && echo "done7" &
curl -s -X POST -d '{"who":"testuser","message":"post number 8.","clock":3}'  http://localhost:8080/api/post && echo "done8" &
curl -s -X POST -d '{"who":"testuser","message":"post number 9.","clock":3}'  http://localhost:8080/api/post && echo "done9" &
curl -s -X POST -d '{"who":"testuser","message":"post number 10.","clock":3}'  http://localhost:8080/api/post && echo "done10" &
curl -s -X POST -d '{"who":"testuser","message":"post number 11.","clock":3}'  http://localhost:8080/api/post && echo "done11" &
curl -s -X POST -d '{"who":"testuser","message":"post number 12.","clock":3}'  http://localhost:8080/api/post && echo "done12" &
curl -s -X POST -d '{"who":"testuser","message":"post number 13.","clock":3}'  http://localhost:8080/api/post && echo "done13" &
curl -s -X POST -d '{"who":"testuser","message":"post number 14.","clock":3}'  http://localhost:8080/api/post && echo "done14" &
curl -s -X POST -d '{"who":"testuser","message":"post number 15.","clock":3}'  http://localhost:8080/api/post && echo "done15" &
curl -s -X POST -d '{"who":"testuser","message":"post number 16.","clock":3}'  http://localhost:8080/api/post && echo "done16" &
curl -s -X POST -d '{"who":"testuser","message":"post number 17.","clock":3}'  http://localhost:8080/api/post && echo "done17" &
curl -s -X POST -d '{"who":"testuser","message":"post number 18.","clock":3}'  http://localhost:8080/api/post && echo "done18" &
curl -s -X POST -d '{"who":"testuser","message":"post number 19.","clock":3}'  http://localhost:8080/api/post && echo "done19" &
curl -s -X POST -d '{"who":"testuser","message":"post number 20.","clock":3}'  http://localhost:8080/api/post && echo "done20" &
curl -s -X POST -d '{"who":"testuser","message":"post number 21.","clock":3}'  http://localhost:8080/api/post && echo "done21" &
curl -s -X POST -d '{"who":"testuser","message":"post number 22.","clock":3}'  http://localhost:8080/api/post && echo "done22" &
curl -s -X POST -d '{"who":"testuser","message":"post number 23.","clock":3}'  http://localhost:8080/api/post && echo "done23" &
curl -s -X POST -d '{"who":"testuser","message":"post number 24.","clock":3}'  http://localhost:8080/api/post && echo "done24" &
curl -s -X POST -d '{"who":"testuser","message":"post number 25.","clock":3}'  http://localhost:8080/api/post && echo "done25" &
curl -s -X POST -d '{"who":"testuser","message":"post number 26.","clock":3}'  http://localhost:8080/api/post && echo "done26" &
curl -s -X POST -d '{"who":"testuser","message":"post number 27.","clock":3}'  http://localhost:8080/api/post && echo "done27" &
curl -s -X POST -d '{"who":"testuser","message":"post number 28.","clock":3}'  http://localhost:8080/api/post && echo "done28" &
curl -s -X POST -d '{"who":"testuser","message":"post number 29.","clock":3}'  http://localhost:8080/api/post && echo "done29" &
curl -s -X POST -d '{"who":"testuser","message":"post number 30.","clock":3}'  http://localhost:8080/api/post && echo "done30" &
curl -s -X POST -d '{"who":"testuser","message":"post number 31.","clock":3}'  http://localhost:8080/api/post && echo "done31" &
curl -s -X POST -d '{"who":"testuser","message":"post number 32.","clock":3}'  http://localhost:8080/api/post && echo "done32" &
curl -s -X POST -d '{"who":"testuser","message":"post number 33.","clock":3}'  http://localhost:8080/api/post && echo "done33" &
curl -s -X POST -d '{"who":"testuser","message":"post number 34.","clock":3}'  http://localhost:8080/api/post && echo "done34" &
curl -s -X POST -d '{"who":"testuser","message":"post number 35.","clock":3}'  http://localhost:8080/api/post && echo "done35" &
curl -s -X POST -d '{"who":"testuser","message":"post number 36.","clock":3}'  http://localhost:8080/api/post && echo "done36" &
curl -s -X POST -d '{"who":"testuser","message":"post number 37.","clock":3}'  http://localhost:8080/api/post && echo "done37" &
curl -s -X POST -d '{"who":"testuser","message":"post number 38.","clock":3}'  http://localhost:8080/api/post && echo "done38" &
curl -s -X POST -d '{"who":"testuser","message":"post number 39.","clock":3}'  http://localhost:8080/api/post && echo "done39" &
curl -s -X POST -d '{"who":"testuser","message":"post number 40.","clock":3}'  http://localhost:8080/api/post && echo "done40" &
curl -s -X POST -d '{"who":"testuser","message":"post number 41.","clock":3}'  http://localhost:8080/api/post && echo "done41" &
curl -s -X POST -d '{"who":"testuser","message":"post number 42.","clock":3}'  http://localhost:8080/api/post && echo "done42" &
curl -s -X POST -d '{"who":"testuser","message":"post number 43.","clock":3}'  http://localhost:8080/api/post && echo "done43" &
curl -s -X POST -d '{"who":"testuser","message":"post number 44.","clock":3}'  http://localhost:8080/api/post && echo "done44" &
curl -s -X POST -d '{"who":"testuser","message":"post number 45.","clock":3}'  http://localhost:8080/api/post && echo "done45" &
curl -s -X POST -d '{"who":"testuser","message":"post number 46.","clock":3}'  http://localhost:8080/api/post && echo "done46" &
curl -s -X POST -d '{"who":"testuser","message":"post number 47.","clock":3}'  http://localhost:8080/api/post && echo "done47" &
curl -s -X POST -d '{"who":"testuser","message":"post number 48.","clock":3}'  http://localhost:8080/api/post && echo "done48" &
curl -s -X POST -d '{"who":"testuser","message":"post number 49.","clock":3}'  http://localhost:8080/api/post && echo "done49" &
curl -s -X POST -d '{"who":"testuser","message":"post number 50.","clock":3}'  http://localhost:8080/api/post && echo "done50" &
curl -s -X POST -d '{"who":"testuser","message":"post number 51.","clock":3}'  http://localhost:8080/api/post && echo "done51" &
curl -s -X POST -d '{"who":"testuser","message":"post number 52.","clock":3}'  http://localhost:8080/api/post && echo "done52" &
curl -s -X POST -d '{"who":"testuser","message":"post number 53.","clock":3}'  http://localhost:8080/api/post && echo "done53" &
curl -s -X POST -d '{"who":"testuser","message":"post number 54.","clock":3}'  http://localhost:8080/api/post && echo "done54" &
curl -s -X POST -d '{"who":"testuser","message":"post number 55.","clock":3}'  http://localhost:8080/api/post && echo "done55" &
curl -s -X POST -d '{"who":"testuser","message":"post number 56.","clock":3}'  http://localhost:8080/api/post && echo "done56" &
curl -s -X POST -d '{"who":"testuser","message":"post number 57.","clock":3}'  http://localhost:8080/api/post && echo "done57" &
curl -s -X POST -d '{"who":"testuser","message":"post number 58.","clock":3}'  http://localhost:8080/api/post && echo "done58" &
curl -s -X POST -d '{"who":"testuser","message":"post number 59.","clock":3}'  http://localhost:8080/api/post && echo "done59" &
curl -s -X POST -d '{"who":"testuser","message":"post number 60.","clock":3}'  http://localhost:8080/api/post && echo "done60" &
curl -s -X POST -d '{"who":"testuser","message":"post number 61.","clock":3}'  http://localhost:8080/api/post && echo "done61" &
curl -s -X POST -d '{"who":"testuser","message":"post number 62.","clock":3}'  http://localhost:8080/api/post && echo "done62" &
curl -s -X POST -d '{"who":"testuser","message":"post number 63.","clock":3}'  http://localhost:8080/api/post && echo "done63" &
curl -s -X POST -d '{"who":"testuser","message":"post number 64.","clock":3}'  http://localhost:8080/api/post && echo "done64" &
curl -s -X POST -d '{"who":"testuser","message":"post number 65.","clock":3}'  http://localhost:8080/api/post && echo "done65" &
curl -s -X POST -d '{"who":"testuser","message":"post number 66.","clock":3}'  http://localhost:8080/api/post && echo "done66" &
curl -s -X POST -d '{"who":"testuser","message":"post number 67.","clock":3}'  http://localhost:8080/api/post && echo "done67" &
curl -s -X POST -d '{"who":"testuser","message":"post number 68.","clock":3}'  http://localhost:8080/api/post && echo "done68" &
curl -s -X POST -d '{"who":"testuser","message":"post number 69.","clock":3}'  http://localhost:8080/api/post && echo "done69" &
curl -s -X POST -d '{"who":"testuser","message":"post number 70.","clock":3}'  http://localhost:8080/api/post && echo "done70" &
curl -s -X POST -d '{"who":"testuser","message":"post number 71.","clock":3}'  http://localhost:8080/api/post && echo "done71" &
curl -s -X POST -d '{"who":"testuser","message":"post number 72.","clock":3}'  http://localhost:8080/api/post && echo "done72" &
curl -s -X POST -d '{"who":"testuser","message":"post number 73.","clock":3}'  http://localhost:8080/api/post && echo "done73" &
curl -s -X POST -d '{"who":"testuser","message":"post number 74.","clock":3}'  http://localhost:8080/api/post && echo "done74" &
curl -s -X POST -d '{"who":"testuser","message":"post number 75.","clock":3}'  http://localhost:8080/api/post && echo "done75" &
curl -s -X POST -d '{"who":"testuser","message":"post number 76.","clock":3}'  http://localhost:8080/api/post && echo "done76" &
curl -s -X POST -d '{"who":"testuser","message":"post number 77.","clock":3}'  http://localhost:8080/api/post && echo "done77" &
curl -s -X POST -d '{"who":"testuser","message":"post number 78.","clock":3}'  http://localhost:8080/api/post && echo "done78" &
curl -s -X POST -d '{"who":"testuser","message":"post number 79.","clock":3}'  http://localhost:8080/api/post && echo "done79" &
curl -s -X POST -d '{"who":"testuser","message":"post number 80.","clock":3}'  http://localhost:8080/api/post && echo "done80" &
curl -s -X POST -d '{"who":"testuser","message":"post number 81.","clock":3}'  http://localhost:8080/api/post && echo "done81" &
curl -s -X POST -d '{"who":"testuser","message":"post number 82.","clock":3}'  http://localhost:8080/api/post && echo "done82" &
curl -s -X POST -d '{"who":"testuser","message":"post number 83.","clock":3}'  http://localhost:8080/api/post && echo "done83" &
curl -s -X POST -d '{"who":"testuser","message":"post number 84.","clock":3}'  http://localhost:8080/api/post && echo "done84" &
curl -s -X POST -d '{"who":"testuser","message":"post number 85.","clock":3}'  http://localhost:8080/api/post && echo "done85" &
curl -s -X POST -d '{"who":"testuser","message":"post number 86.","clock":3}'  http://localhost:8080/api/post && echo "done86" &
curl -s -X POST -d '{"who":"testuser","message":"post number 87.","clock":3}'  http://localhost:8080/api/post && echo "done87" &
curl -s -X POST -d '{"who":"testuser","message":"post number 88.","clock":3}'  http://localhost:8080/api/post && echo "done88" &
curl -s -X POST -d '{"who":"testuser","message":"post number 89.","clock":3}'  http://localhost:8080/api/post && echo "done89" &
curl -s -X POST -d '{"who":"testuser","message":"post number 90.","clock":3}'  http://localhost:8080/api/post && echo "done90" &
curl -s -X POST -d '{"who":"testuser","message":"post number 91.","clock":3}'  http://localhost:8080/api/post && echo "done91" &
curl -s -X POST -d '{"who":"testuser","message":"post number 92.","clock":3}'  http://localhost:8080/api/post && echo "done92" &
curl -s -X POST -d '{"who":"testuser","message":"post number 93.","clock":3}'  http://localhost:8080/api/post && echo "done93" &
curl -s -X POST -d '{"who":"testuser","message":"post number 94.","clock":3}'  http://localhost:8080/api/post && echo "done94" &
curl -s -X POST -d '{"who":"testuser","message":"post number 95.","clock":3}'  http://localhost:8080/api/post && echo "done95" &
curl -s -X POST -d '{"who":"testuser","message":"post number 96.","clock":3}'  http://localhost:8080/api/post && echo "done96" &
curl -s -X POST -d '{"who":"testuser","message":"post number 97.","clock":3}'  http://localhost:8080/api/post && echo "done97" &
curl -s -X POST -d '{"who":"testuser","message":"post number 98.","clock":3}'  http://localhost:8080/api/post && echo "done98" &
curl -s -X POST -d '{"who":"testuser","message":"post number 99.","clock":3}'  http://localhost:8080/api/post && echo "done99" &
curl -s -X POST -d '{"who":"testuser","message":"post number 100.","clock":3}'  http://localhost:8080/api/post && echo "done100" &

wait